---
seed: 3
dataset: &d_name CVE-2014-0160
data:
    prefix: &d_prefix data 
    raw: &d_raw !join [*d_prefix, raw]
    processed: &d_processed !join [*d_prefix, processed, *d_name]
    interim: !join [*d_prefix, interim, *d_name]
    runs: !join [*d_raw, *d_name, runs.csv]
    scenarios: !join [*d_raw, *d_name]
model:
    prior: 1
    time_delta: 99999999
    prefix: &m_prefix models
    paths: !join [*d_processed, temp_paths_410.p]
    save: !join [*m_prefix, *d_name]
    train_examples: 1
    max_order: 3
simulate:
    normal_samples: 10
    attack_samples: 10
    list_attacks:
    model: !join [*m_prefix, *d_name, MOM_2_delta_410_prior_1.p]
    threshold: -100
c_results:
    prefix: experiments
    timestamp: yes
pathpy:
    min_severity: 3
