---
seed: 3
dataset: &d_name CVE-2014-0160
data:
    prefix: &d_prefix data 
    raw: &d_raw !join [*d_prefix, raw]
    processed: &d_processed !join [*d_prefix, processed, *d_name]
    interim: !join [*d_prefix, interim, *d_name]
    runs: !join [*d_raw, *d_name, runs.csv]
    scenarios: !join [*d_raw, *d_name]
model:
    time_delta: 100
    prefix: &m_prefix models
    paths: !join [*d_processed, temp_paths_10.p]
    save: !join [*m_prefix, *d_name]
    train_examples: 10
    max_order: 5
simulate:
    normal_samples: 10
    attack_samples: 10
    list_attacks:
        - lively_varahamihira_7505
        - harsh_mayer_6075
    model: !join [*m_prefix, *d_name, MOM_delta_100.p]
    threshold: -100
c_results:
    prefix: experiments
    timestamp: yes
pathpy:
    min_severity: 3
