---
seed: 42
data:
    prefix: data
    name: CVE-2017-7529
    runs: runs.csv
features:
    intermediate_path: data
    time_delta: 10
detector:
    exploit: no
    prefix: data
    model: temp_paths_30.p
results:
    prefix: experiments
    timestamp: yes
training:
    learning_rate: 1e-3
    adam_eps: 1e-8
    eval_batch_size: 128
    train_batch_size: 128
    test_batch_size: 128
    num_epochs": 10
